conda install tensorflow-gpu=2.0.0
pip install tensorflow-estimator==2.0.0
conda install keras=2.3.1
pip install streamlit
pip install streamlit-aggrid
pip install opencv-python
pip uninstall scikit-learn
pip install scikit-learn==0.20.4
pip install pycm
conda deactivate streamlit-calciumgan
